@startuml

left to right direction

actor "Гость" as Guest
actor "Пользователь" as User

rectangle "Интернет-магазин" {
  Guest -- (Просмотр каталога)
  Guest -- (Авторизация)

  User -- (Просмотр каталога)
  User -- (Добавление в корзину)
  User -- (Оставление отзыва)
  User -- (Оформление заказа)
  User -- (Скачивание файла)
}

(Авторизация) <|-- (Оформление заказа)
@enduml
